Features/reactions
Sous-Vide-Zen/backend pull request #17
Opened 2023-11-16 15:32 UTC by aleha2001

2023-11-18 10:04 UTC, vBaMnup requested changes

2023-11-18 10:04 UTC, vBaMnup commented on src/apps/reactions/models.py
> +    emoji = models.CharField(choices=EmojyChoice.choices, max_length=10)
blank=true и default для создания экземпляра модели с пустым значением

2023-11-18 10:04 UTC, vBaMnup commented on src/apps/reactions/models.py
> +    limit_models = models.Q(app_label="recipes", model="recipe") | models.Q(
это зачем?

2023-11-18 10:04 UTC, vBaMnup commented on src/apps/reactions/models.py
> +        ]
Сделай проверку на уникальность автора, реакции, типа обЪекта и id обекта

2023-11-18 10:04 UTC, vBaMnup commented on src/apps/reactions/choices.py
> +class EmojyChoice(models.TextChoices):
Давай использовать просто названия LIKE = "Like", остальное на фронте сделают

2023-11-20 18:01 UTC, aleha2001 commented on src/apps/reactions/models.py
> +        ]
Хорошая идея, добавил

2023-11-20 18:03 UTC, alehakad commented on src/apps/reactions/choices.py
> +class EmojyChoice(models.TextChoices):
Ок

2023-11-20 18:07 UTC, alehakad commented on src/apps/reactions/models.py
> +    limit_models = models.Q(app_label="recipes", model="recipe") | models.Q(
Чтобы рекации можно было ставить только на определенные модели: на рецепты или на комментарии

2023-11-20 18:18 UTC, aleha2001 commented on src/apps/reactions/models.py
> +    emoji = models.CharField(choices=EmojyChoice.choices, max_length=10)
Это про какое поле?

2023-11-27 14:05 UTC, vBaMnup commented on src/apps/reactions/models.py
> +    limit_models = models.Q(app_label="recipes", model="recipe") | models.Q(
а тогда что в content_type?

2023-11-27 14:06 UTC, vBaMnup commented on src/apps/reactions/models.py
> +    emoji = models.CharField(choices=EmojyChoice.choices, max_length=10)
emoji чтобы можно было просто на кнопку нажать и поставить дефолтный эмодзи (сердце, например)

2023-11-27 14:08 UTC, vBaMnup requested changes
Необходимы правки

2023-11-29 13:10 UTC, alehakad commented on src/apps/reactions/models.py
> +    emoji = models.CharField(choices=EmojyChoice.choices, max_length=10)
Ок, добавил

2023-11-29 13:14 UTC, alehakad commented on src/apps/reactions/models.py
> +    limit_models = models.Q(app_label="recipes", model="recipe") | models.Q(
content_type ссылается на модель, к объекту которой ставится реакция, limit_choices_to ограничивает выбор моделей

2023-11-30 12:49 UTC, merged