Category model added
Sous-Vide-Zen/backend pull request #24
Opened 2023-11-29 15:37 UTC by aleha2001

2023-11-30 13:00 UTC, vBaMnup requested changes

2023-11-30 13:00 UTC, vBaMnup commented on src/apps/recipes/models.py
> +    category = models.ManyToManyField("Category", related_name="recipes")
Рецепты могут быть и большинство будут без категории

2023-12-03 14:03 UTC, alehakad commented on src/apps/recipes/models.py
> +    category = models.ManyToManyField("Category", related_name="recipes")
Добавил blank=True

2023-12-05 07:37 UTC, vBaMnup commented on src/apps/recipes/models.py
> +    category = models.ManyToManyField("Category", related_name="recipes")
а Null?))

2023-12-05 15:38 UTC, alehakad commented on src/apps/recipes/models.py
> +    category = models.ManyToManyField("Category", related_name="recipes")
null=True ничего не меняет для ManyToManyField (если нет категорий - то просто ноль строчек в таблице)

2023-12-06 14:07 UTC, merged