Features/recipes
Sous-Vide-Zen/backend pull request #3
Opened 2023-10-30 16:36 UTC by aleha2001

Recipes model added

2023-10-30 17:44 UTC, vBaMnup requested changes

2023-10-30 17:44 UTC, vBaMnup commented on src/apps/recipes/models.py
> +
Используй User = get_user_model() для получения модели пользователя

2023-10-30 17:44 UTC, vBaMnup commented on src/apps/recipes/models.py
> +    title = models.CharField(max_length=500)
давай сократим название до 150 символов

2023-10-30 17:44 UTC, vBaMnup commented on src/apps/recipes/models.py
> +        self.short_text = self.full_text[:100]  # TODO: round by word?
yes

2023-10-30 19:06 UTC, aleha2001 commented on src/apps/recipes/models.py
> +
Вообще в доке пишут, что в ForeignKey лучше так ссылаться: settings.AUTH_USER_MODEL ))

2023-11-04 09:12 UTC, vBaMnup requested changes

2023-11-04 09:12 UTC, vBaMnup commented on src/apps/recipes/models.py
> +    def save(self, *args, **kwargs):
Перенеси функцию сокращения текста в файл src/apps/api/services.py

2023-11-04 09:49 UTC, aleha2001 commented on src/apps/recipes/models.py
> +    def save(self, *args, **kwargs):
Ок, перенес

2023-11-04 11:49 UTC, vBaMnup approved these changes

2023-11-04 11:50 UTC, merged