Recipe slug saving changed
Sous-Vide-Zen/backend pull request #31
Opened 2023-12-16 14:30 UTC by aleha2001

2023-12-21 06:28 UTC, vBaMnup requested changes

2023-12-21 06:28 UTC, vBaMnup commented on src/apps/recipes/models.py
> +        same_recipes = Recipe.objects.filter(title=self.title).count()
Давай не будем хардкодить сюда Recipe (вдруг у нас название изменится) используй self

2023-12-21 17:30 UTC, aleha2001 commented on src/apps/recipes/models.py
> +        same_recipes = Recipe.objects.filter(title=self.title).count()
Мне тут нужно посчитать количество рецептов с таким же названием. Возможно по другому, без использования Recipe?

2023-12-24 13:58 UTC, vBaMnup commented on src/apps/recipes/models.py
> +        same_recipes = Recipe.objects.filter(title=self.title).count()
Да, в данном случае ты для подсчета используешь название модели, а что если мы название поменяем по какой-то причине? тогда и тут придется менять, если не забудем) поэтому получай имя модели с помощью self

2023-12-24 16:22 UTC, aleha2001 commented on src/apps/recipes/models.py
> +        same_recipes = Recipe.objects.filter(title=self.title).count()
Ок

2023-12-25 19:00 UTC, merged