add get, patch, delete endpoint for user/username, with permissions
Sous-Vide-Zen/backend pull request #47
Opened 2024-01-23 16:28 UTC by exites

2024-01-25 17:44 UTC, vBaMnup requested changes

2024-01-25 17:44 UTC, vBaMnup commented on src/apps/users/serializers.py
> +        user_model = get_user_model()
Модель юзера достаточно получить один раз

2024-01-25 17:44 UTC, vBaMnup commented on src/apps/users/serializers.py
> +            .exclude(id=self.instance.id)
Сразу в фильтре нельзя указать id?

2024-01-25 17:44 UTC, vBaMnup commented on src/apps/users/views.py
> +    @action(["get", "put", "patch", "delete"], detail=False)
можно сделать что-то типа такого:

    serializer_class = CustomUserMeSerializer

    def get_serializer_class(self):
        if self.action == "me":
            return CustomUserMeSerializer
        return super().get_serializer_class()
        
и вот такой урл добавить перед джозером:
path("users/me/", CustomUserNEViewSet.as_view({"get": "me"}), name="user-me"),

2024-01-25 17:44 UTC, vBaMnup commented on src/apps/users/views.py
> +class CustomUserViewSet(viewsets.ModelViewSet):
Давай попробуем во вьюсете никакие методы не переопределять, если очень надо, то лучше сделать это в сериализаторе

2024-01-30 03:37 UTC, exites commented on src/apps/users/serializers.py
> +            .exclude(id=self.instance.id)
Эту часть кода вообще убрал, так как джанга сама делает проверку уникальности поля юзернейм

2024-01-30 03:48 UTC, exites commented on src/apps/users/views.py
> +    @action(["get", "put", "patch", "delete"], detail=False)
Получилось другим вариантом переопределить и убрать остальные методы из свагера. Нужно потестить

2024-01-30 04:34 UTC, exites commented on src/apps/users/views.py
> +class CustomUserViewSet(viewsets.ModelViewSet):
Да, тут тоже убрал весь код с переопределением, создал новый файл с пермишином и тем самым вынес логику из вьюхи

2024-01-30 05:14 UTC, exites commented on src/apps/users/views.py
> +    @action(["get", "put", "patch", "delete"], detail=False)
Потестил, патч не работает. 
![image](https://github.com/Sous-Vide-Zen/backend/assets/93001573/6c358247-bb13-46a8-afb9-e50dcc352c72)

2024-01-30 09:12 UTC, vBaMnup requested changes
Надо убрать джозеровские урлы auth/users и auth/users/{id}

2024-01-30 09:12 UTC, vBaMnup commented on src/apps/users/permissions.py
> +from rest_framework.permissions import BasePermission
давай все пермишны вынесем в src/base/permission.py

2024-01-30 09:12 UTC, vBaMnup commented on src/apps/users/models.py
>  from django.core.validators import FileExtensionValidator
сделай миграции :)

2024-01-30 09:12 UTC, vBaMnup commented on src/apps/users/permissions.py
> +    def has_object_permission(self, request, view, obj):
просматривать авторов могут неавторизированные пользователи

2024-02-08 14:51 UTC, merged