Users/username
Sous-Vide-Zen/backend pull request #53
Opened 2024-02-16 09:57 UTC by exites

2024-02-21 09:07 UTC, vBaMnup requested changes
У нас все еще требуется username при регистрации пользователя.
Удали эндпоинт POST http://127.0.0.1:8000/api/v1/user/

2024-02-21 09:07 UTC, vBaMnup commented on src/apps/users/models.py
> +        if not self.username:  # если username не задан
давай будем использовать случайное 6-тизначное число. И создай отдельную функцию для генерации username

2024-02-24 21:12 UTC, exites commented
> У нас все еще требуется username при регистрации пользователя

А где требуется? В модели он помечен как blank = true, null = true. В сваггере он не помочен как required

2024-02-26 13:01 UTC, vBaMnup requested changes
По всему приложению Users, добавь докстринги.

2024-02-26 13:01 UTC, vBaMnup commented on src/apps/users/routes/django_urls.py
> +# router.register(r"users", CustomUserViewSet, basename="user")
для запроса списка пользователей, используем endpoint /userS

2024-02-26 13:01 UTC, vBaMnup commented on src/apps/users/routes/django_urls.py
> +user_detail_view = CustomUserViewSet.as_view(
не используем PUT

2024-02-26 13:01 UTC, vBaMnup commented on src/apps/users/utils.py
> +def generate_username(user_id):
Добавь докстрингу и тайпхинты

2024-02-26 13:01 UTC, vBaMnup commented on src/apps/users/utils.py
> +        CustomUser,
Давай модель предадим в функцию

2024-02-26 13:01 UTC, vBaMnup commented on src/apps/users/views.py
> +    http_method_names = ["get", "put", "patch", "delete", "head", "options", "trace"]
Разве мы используем столько методов?

2024-02-28 17:31 UTC, exites commented on src/apps/users/routes/django_urls.py
> +# router.register(r"users", CustomUserViewSet, basename="user")
Это в следующем коммите будет исправлено

2024-03-05 15:44 UTC, merged