Follow/views
Sous-Vide-Zen/backend pull request #55
Opened 2024-02-24 11:19 UTC by mtedoradze

Fixed 2 bags for [Follow]: 1 - modified format of a message if the subscription already exists; 2 - added a message of success when unsubscribe.

2024-02-24 18:03 UTC, vBaMnup requested changes

2024-02-24 18:03 UTC, vBaMnup commented on src/apps/follow/views.py
> +            data={"message": "Вы успешно отписались от автора"},
Добавь в тесты

2024-02-24 18:03 UTC, vBaMnup commented on .DS_Store
Это что за файл? Удали)

2024-02-24 18:03 UTC, vBaMnup commented on src/apps/follow/views.py
> +            return Response(
Давай попробуем перенести логику ответов сериализатор :)

2024-02-29 12:33 UTC, vBaMnup requested changes

2024-02-29 12:33 UTC, vBaMnup commented on src/apps/follow/serializers.py
> +        queryset = Follow.objects.filter(user=user, author=author)
И тут используем .exists() :)

2024-02-29 17:52 UTC, mtedoradze commented on src/apps/follow/serializers.py
> +        queryset = Follow.objects.filter(user=user, author=author)
не поняла, где? нам же вроде нужен queryset здесь, а не bool, чтобы проверить количество объектов...

2024-02-29 18:19 UTC, vBaMnup commented on src/apps/follow/serializers.py
> +        queryset = Follow.objects.filter(user=user, author=author)
А зачем мы проверяем количество объектов?

2024-03-01 10:43 UTC, merged