Added views, serializers and urls for recipe's reactions
Sous-Vide-Zen/backend pull request #65
Opened 2024-03-11 22:12 UTC by mtedoradze

2024-03-12 12:12 UTC, vBaMnup requested changes
Хорошо, но есть что улучшить :)

2024-03-12 12:12 UTC, vBaMnup commented on src/apps/reactions/urls.py
> +router.register(
Лишние методы для реакций. Должны быть только GET (list), CREATE, DELETE

2024-03-12 12:12 UTC, vBaMnup commented on src/apps/reactions/views.py
> +    throttle_scope = "reactions"
Добавь swagger_tags = ["Reactions"] для разделения в swager

2024-03-12 12:12 UTC, vBaMnup commented on src/apps/reactions/views.py
> +        queryset = Recipe.objects.filter(id=recipe.id)
Фильтруй сразу по слагу, рецепт получать не нужно

2024-03-12 12:12 UTC, vBaMnup commented on src/apps/reactions/views.py
> +        if created == False and reaction.is_deleted == False:
можно улучшить читаемость: if not created and not reaction.is_deleted:

2024-03-12 12:12 UTC, vBaMnup commented on src/apps/reactions/views.py
> +                status=403,
Статус получай из джанговских статусов HTTP_403_FORBIDDEN

2024-03-12 12:12 UTC, vBaMnup commented on src/apps/reactions/views.py
> +        elif reaction.is_deleted == True:
elif не нужен, ведь у нас есть return, в случае если выполняется предудущее условие

2024-03-12 12:12 UTC, vBaMnup commented on src/apps/reactions/views.py
> +        return Response({"message": "Вы оценили рецепт!"}, status=201)
Статус :)

2024-03-12 12:12 UTC, vBaMnup commented on src/apps/reactions/views.py
> +        reaction = get_object_or_404(Reaction, id=kwargs.get("pk"), object_id=recipe.id)
а мы можем сразу получить реакцию, не получая рецепт?

2024-03-12 12:12 UTC, vBaMnup commented on src/apps/reactions/views.py
> +                {"detail": "You do not have permission to perform this action."},
Все ответы сервера теперь делаем на русском)

2024-03-12 12:12 UTC, vBaMnup commented on src/apps/reactions/views.py
> +                status=403,
Статус :)

2024-03-12 12:12 UTC, vBaMnup commented on src/apps/reactions/views.py
> +        return Response({"message": "Реакция отменена!"}, status=204)
и тут статус :)

2024-03-12 17:28 UTC, mtedoradze commented on src/apps/reactions/views.py
> +        reaction = get_object_or_404(Reaction, id=kwargs.get("pk"), object_id=recipe.id)
Можем, но тогда не пойму, как проверить, что в урле указан слаг существующего рецепта...

2024-03-13 18:25 UTC, vBaMnup requested changes

2024-03-13 18:25 UTC, vBaMnup commented on src/apps/reactions/views.py
> +        queryset = get_list_or_404(Recipe, slug=self.kwargs.get("slug"))
Почему list? мы же получаем один рецепт)

2024-03-13 18:25 UTC, vBaMnup commented on src/apps/reactions/views.py
Рецепт получаем из кверисета вместо: recipe = get_object_or_404(Recipe, slug=kwargs.get("slug"))

2024-03-13 18:25 UTC, vBaMnup commented on src/apps/reactions/views.py
> +            Reaction, id=kwargs.get("pk"), recipe_reactions__slug=kwargs.get("slug")
не надо ли нам в фильтр еще и автора добавить?)

2024-03-13 19:40 UTC, mtedoradze commented on src/apps/reactions/views.py
> +        queryset = get_list_or_404(Recipe, slug=self.kwargs.get("slug"))
А если один рецепт получим, то метод get_queryset не будет работать...он же должен возвращать кверисет, а не объект

2024-03-15 20:59 UTC, closed without merging