Added view-functions and serializer for favorites in apps/recipes
Sous-Vide-Zen/backend pull request #77
Opened 2024-03-29 07:12 UTC by mtedoradze

2024-03-29 11:43 UTC, vBaMnup requested changes
Умничка, Маша) Небольшие правки остались 👍

2024-03-29 11:43 UTC, vBaMnup commented on src/apps/recipes/views.py
>      def get_serializer_class(self):
давай используем словарь, чтобы избавиться от длинной конструкции if-elif-else

2024-03-29 11:43 UTC, vBaMnup commented on src/apps/recipes/views.py
> +        """Добавление рецепта в избранное/удаление из избранного."""
Докстринга везде на английском :)

2024-03-29 11:43 UTC, vBaMnup commented on src/apps/recipes/views.py
> +        favorite_recipe = Favorite.objects.filter(author=request.user, recipe=recipe)
Дальше все сильно упростим, если будем использовать метод get_or_create

2024-03-29 11:43 UTC, vBaMnup commented on src/tests/favorite/test_favorite_views.py
> +    def test_favorite_recipe_creation(self, api_client, new_user, new_recipe):
Разбей разные случаи на отдельные тесты для наглядности

2024-03-29 11:43 UTC, vBaMnup commented on src/tests/favorite/test_favorite_views.py
> +    def test_favorite_recipe_deletion(self, api_client, new_author, new_recipe):
и тут тоже

2024-03-30 17:46 UTC, mtedoradze commented on src/apps/recipes/views.py
>      def get_serializer_class(self):
Постаралась, но не получилось полностью избавиться от if-else(

2024-03-31 20:36 UTC, vBaMnup approved these changes

2024-03-31 20:36 UTC, merged