Fix/code file
Sous-Vide-Zen/backend pull request #88
Opened 2024-05-08 08:47 UTC by menma331

All responses text from view answers has been carried over to base file.

2024-05-16 19:58 UTC, mtedoradze reviewed
Привет!) несколько незначительных моментов нашла, а так - все гуд :)

2024-05-16 19:58 UTC, mtedoradze commented on src/base/code_text.py
> +PAGE_NOT_FOUND = {"detail": "Страница не найдена."}
Тут тоже ": dict =" надо добавить

2024-05-16 19:58 UTC, mtedoradze commented on src/base/code_text.py
> +RECIPE_CAN_BE_EDIT_ONLY_ONCE_PER_DAY = {
и тут ": dict ="

2024-05-16 19:58 UTC, mtedoradze commented on src/base/code_text.py
> +THE_LIST_OF_CHOOSE_FAVORITES_RECIPES_IS_EMPTY: dict = {
Тут слово "CHOOSE" можно убрать - оно лишнее

2024-05-16 19:58 UTC, mtedoradze commented on src/apps/comments/views.py
> +                raise ValidationError(INVALID_ID_FORMAT)
Ниже в коде (напр. файл services.py) ты добавляешь еще "code=" - лучше сделать единообразно.

2024-05-16 19:58 UTC, mtedoradze commented on src/apps/comments/views.py
> +            raise NotFound(COMMENT_NOT_FOUND)
и здесь не хватает "code=".

2024-05-16 19:58 UTC, mtedoradze commented on src/apps/recipes/views.py
> +            return Response(THE_LIST_OF_CHOOSE_FAVORITES_RECIPES_IS_EMPTY)
Тут слово "CHOOSE" можно убрать - оно лишнее.

2024-05-19 19:37 UTC, mtedoradze reviewed
Привет! Придется еще кое-что поправить, чтобы было совсем хорошо :)

2024-05-19 19:37 UTC, mtedoradze commented on src/base/code_text.py
> +PASSWORDS_IS_NOT_SIMILAR: dict = {"password": "Пароли не совпадают!"}
тут нужно либо "ARE" вместо "IS", либо вообще просто "PASSWORDS_NOT_SIMILAR"

2024-05-19 19:37 UTC, mtedoradze commented on src/apps/comments/views.py
> +                raise ValidationError(INVALID_ID_FORMAT, code="invalid")
Для разных ошибок разные коды: здесь, например, "invalid_id"

2024-05-19 19:37 UTC, mtedoradze commented on src/apps/comments/views.py
> +            raise NotFound(COMMENT_NOT_FOUND)
Здесь тоже надо добавить что-то вроде code="comment_not_found"

2024-05-19 19:37 UTC, mtedoradze commented on src/apps/follow/views.py
> +                data=USER_DOES_NOT_EXISTS,
"USER_DOES_NOT_EXIST" вместо "EXISTs"

2024-05-19 19:37 UTC, mtedoradze commented on src/apps/follow/views.py
> +                data=USER_DOES_NOT_EXISTS,
"USER_DOES_NOT_EXIST" вместо "EXISTs"

2024-05-19 19:37 UTC, mtedoradze commented on src/apps/ingredients/serializers.py
> +                AMOUNT_OF_INGREDIENT_LESS_THAN_ZERO, code="invalid"
Для разных ошибок разные коды: здесь, например, "invalid_amount"

2024-05-19 19:37 UTC, mtedoradze commented on src/base/code_text.py
> +RECIPE_CAN_BE_EDIT_ONLY_ONCE_PER_DAY: dict = {
Здесь немного другой смысл ошибки - не один раз в день можно редактировать, а только в течение первых суток...лучше так, наверно: "RECIPE_CAN_BE_EDIT_WITHIN_FIRST_DAY"

2024-05-19 19:37 UTC, mtedoradze commented on src/apps/recipes/serializers.py
> +from src.base.code_text import RECIPE_CAN_BE_EDIT_ONLY_ONCE_PER_DAY
Здесь немного другой смысл ошибки - не один раз в день можно редактировать, а только в течение первых суток...лучше так, наверно: "RECIPE_CAN_BE_EDIT_WITHIN_FIRST_DAY"

2024-05-19 19:37 UTC, mtedoradze commented on src/apps/recipes/serializers.py
> +                RECIPE_CAN_BE_EDIT_ONLY_ONCE_PER_DAY, code="permission denied"
1) Здесь немного другой смысл ошибки - не один раз в день можно редактировать, а только в течение первых суток...лучше так, наверно: "RECIPE_CAN_BE_EDIT_WITHIN_FIRST_DAY"
2) Лучше для разных ошибок разные коды и через нижнее подчеркивание: здесь, например, "restriction_per_day",

2024-05-19 19:37 UTC, mtedoradze commented on src/apps/users/serializers.py
> +from src.base.code_text import PASSWORDS_IS_NOT_SIMILAR
тут нужно либо "ARE" вместо "IS", либо вообще просто "PASSWORDS_NOT_SIMILAR"

2024-05-19 19:37 UTC, mtedoradze commented on src/apps/users/serializers.py
> +                PASSWORDS_IS_NOT_SIMILAR, code="passwords is not similar"
1) тут нужно либо "ARE" вместо "IS", либо вообще просто "PASSWORDS_NOT_SIMILAR"
2) code="passwords_not_similar"

2024-05-19 19:37 UTC, mtedoradze commented on src/base/code_text.py
> +USER_DOES_NOT_EXISTS: dict = {"detail": "Пользователь не существует."}
"USER_DOES_NOT_EXIST" вместо "EXISTs"

2024-05-19 19:37 UTC, mtedoradze commented on src/base/code_text.py
> +LIST_OF_FAVORITES_IS_EMPTY: dict = {"detail": "Список избранных рецептов пуст."}
Повтор стр 55 - та же самая ошибка. Но в этом переводе лучше - предлагаю его оставить.

2024-05-19 19:37 UTC, mtedoradze commented on src/base/services.py
> +        raise ValidationError(CANT_ADD_TWO_SIMILAR_INGREDIENT, code="invalid")
Для разных ошибок разные коды: здесь, например, "unique_ingredient"

2024-05-20 12:22 UTC, menma331 commented on src/base/code_text.py
> +RECIPE_CAN_BE_EDIT_ONLY_ONCE_PER_DAY: dict = {
Ааа... А я думал, что это странно - менять только после прошедшего дня

2024-05-20 13:54 UTC, mtedoradze commented on src/apps/users/serializers.py
> +                PASSWORDS_IS_NOT_SIMILAR, code="passwords is not similar"
тут забыл сделать нижнее подчеркивание в code...

2024-05-20 13:54 UTC, mtedoradze commented on src/apps/users/serializers.py
> +                PASSWORDS_ARE_NOT_SIMILAR, code="passwords are not similar"
тут забыл сделать нижнее подчеркивание в code...

2024-05-20 13:55 UTC, mtedoradze requested changes
В одном месте забыл нижнее подчеркивание добавить - см комментарий

2024-05-23 19:50 UTC, mtedoradze approved these changes

2024-05-26 20:37 UTC, merged