Added published field to Recipe model, relevant serializers and views…
Sous-Vide-Zen/backend pull request #89
Opened 2024-05-12 14:36 UTC by mtedoradze

… for recipe creation and recipe updating were modified

2024-05-15 18:37 UTC, menma331 commented on src/apps/recipes/serializers.py
> +                "Вы можете сохранить не более 3-х черновиков. Удалите ненужный черновик."
Нужно вынести это в отдельный файл с ответами сервера(это обновление из моей ветки).

2024-05-15 18:37 UTC, menma331 commented on src/apps/recipes/serializers.py
>                  "Обновление рецепта возможно только в течение суток после создания."
Это нужно вынести в отдельный файл(code_base)

2024-05-15 18:37 UTC, menma331 commented on src/apps/recipes/serializers.py
> +                "Введите название рецепта перед публикацией."
Это тоже нужно вынести в отдельный файл.

2024-05-15 18:37 UTC, menma331 commented on src/apps/recipes/views.py
> +            {"message": "Рецепт успешно удален."}, status=status.HTTP_204_NO_CONTENT
В отдельный файл(по моему там уже есть такое сообщение, так что нужно просто заменить здесь).

2024-05-15 18:37 UTC, menma331 commented on src/apps/recipes/views.py
>              {"detail": "Рецепт добавлен в избранное."}, status=status.HTTP_201_CREATED
В базовом файле есть ответ для этого.

2024-05-15 18:37 UTC, menma331 commented on src/apps/recipes/views.py
>                  data={"detail": "Учетные данные не были предоставлены."},
Заменить на переменную из code_base.

2024-05-15 18:37 UTC, menma331 commented on src/apps/recipes/views.py
>              data={"detail": "Рецепт удален из избранного."},
Заменить

2024-05-15 18:37 UTC, menma331 commented on src/tests/recipes/test_recipe_urls.py
>          assert response.data == {"detail": "Учетные данные не были предоставлены."}
Заменить на ответ из базового файла.

2024-05-15 18:37 UTC, menma331 commented on src/tests/recipes/test_recipe_urls.py
> +        assert response.data == {"message": "Рецепт успешно удален."}
Заменить.

2024-05-15 18:37 UTC, menma331 commented on src/tests/recipes/test_recipe_urls.py
> +        assert response.data == {"message": "Рецепт успешно удален."}
Заменить.

2024-05-29 08:47 UTC, menma331 approved these changes

2024-06-03 13:50 UTC, vBaMnup requested changes
Привет, Маша. Хорошая работа.
Алгоритм действий такой:
1) мы отправляем Post запрос и создаем пустой рецепт (сейчас я могу создать рецепт с данными, это не нужно)
2) рецепту присвается id и сервисный слаг (сейчас это есть)
3) Далее мы редактируем каждое поле отдельно с помощью PATCH запроса. При редактировании каждого поля мы не возвращаем весь рецепт, а только статус код обуспешном изменении.
4) Публикуем рецепт
===================
При просмотре черновиков давай возвращать не полные черновики, а "Черновик от 10.06.2023", его id и slug.
Может давай будем обновлять слаг только при публикации рецепта :)
=============
Заметил следующее:
 - Рецепт публикуется с незаполненными обязательными полями
 - не загружается изображение
 - еще что-то забыл)
 
 Код пока не смотрел, только логику, интересно почему столько правок в тестах?)

2024-06-07 06:25 UTC, mtedoradze commented
Андрей, учла твои комменты:
1. мы отправляем Post запрос и создаем пустой рецепт, рецепту присвается id и сервисный слаг (сейчас это есть) - сделано
2. Далее мы редактируем каждое поле отдельно с помощью PATCH запроса. При редактировании каждого поля мы не возвращаем весь рецепт, а только статус код обуспешном изменении - сделано
3. Публикуем рецепт - сделано
===================
При просмотре черновиков давай возвращать не полные черновики, а "Черновик от 10.06.2023", его id и slug - сделано 
Может давай будем обновлять слаг только при публикации рецепта? :) - сделано 
=============
Заметил следующее:
Рецепт публикуется с незаполненными обязательными полями - сделано (вроде) - только пока мы можем опубликовать рецепт без ингредиентов - это ок? Могу поправить
не загружается изображение - проверила, вроде загружается
еще что-то забыл) - наверно, вспомнишь, когда эту версию кода будешь проверять ))
Код пока не смотрел, только логику, интересно почему столько правок в тестах?) - думаю, потому, что раньше все тесты проверяли по сути опубликованный рецепт, и там, где опубликованный рецепт, теперь появилось новое поле - пришлось добавлять в ответы.

2024-06-27 12:26 UTC, menma331 requested changes

2024-06-27 12:26 UTC, menma331 commented on src/apps/ingredients/serializers.py
> +from ...base.code_text import AMOUNT_OF_INGREDIENT_LESS_THAN_ZERO
Измените импорт на более понятный, по типу src.base.code

2024-06-27 12:26 UTC, menma331 commented on src/tests/conftest.py
> +def draft_recipe(new_author):
Если это получение объекта рецепта, допишите get_ в начале функции. Так будет понятнее для чего функция. А ещё желательно "->" после функции ставить, чтобы понять при на ведении, что возвращает

2024-06-27 12:26 UTC, menma331 commented on src/tests/conftest.py
> +    Create new draft recipe
Точка в конце

2024-06-27 12:26 UTC, menma331 commented on src/tests/conftest.py
> +    Create new published recipe
Точка в конце

2024-06-27 12:26 UTC, menma331 commented on src/tests/recipes/test_recipe_urls.py
> +        Test for create draft recipe not authenticated
Точка

2024-07-01 12:12 UTC, mtedoradze commented on src/tests/conftest.py
> +def draft_recipe(new_author):
Это создание черновика, сделано однотипно с остальными объектами, используемыми в тестах. Менять название нецелесообразно.

2024-07-01 12:13 UTC, mtedoradze commented on src/tests/conftest.py
> +    Create new draft recipe
Имеет смысл менять все докстринги однотипно, но уже другим коммитом.

2024-07-01 12:13 UTC, mtedoradze commented on src/tests/conftest.py
> +    Create new published recipe
Имеет смысл менять все докстринги однотипно, но уже другим коммитом.

2024-07-13 15:43 UTC, mtedoradze commented
Максим, давай откатим коммит с default=True в файле src/apps/recipes/models.py

2024-07-17 12:11 UTC, vBaMnup requested changes
1) Принимается рецепт без ингредиентов, но это у нас обязательное поле!
2) Стоит добавить возможность просмотра черновика с заполненными полями, если по какой-то причине пользователь ранее закрыл черновик и решил продолжить заполнение через какое-то время

2025-02-23 20:42 UTC, closed without merging