Features/comments
Sous-Vide-Zen/backend pull request #9
Opened 2023-11-06 21:03 UTC by aleha2001

2023-11-08 16:53 UTC, vBaMnup requested changes

2023-11-08 16:53 UTC, vBaMnup commented on src/apps/comments/models.py
> +    user = models.ForeignKey(
тут и далее в проекте on_delete=SET_NULL, кроме случаев когда это будет необходимо

2023-11-08 16:53 UTC, vBaMnup commented on src/apps/comments/models.py
> +    user = models.ForeignKey(
author))

2023-11-08 16:53 UTC, vBaMnup commented on src/apps/comments/models.py
> +    timestamp = models.DateTimeField(auto_now_add=True)
Вообще посмотри, я в жире в описании писал какие поля и как назвать)

2023-11-09 17:05 UTC, aleha2001 commented on src/apps/comments/models.py
> +    timestamp = models.DateTimeField(auto_now_add=True)
Ок, я на файл тз ориентировался

2023-11-18 08:49 UTC, merged