feat: All factories have been moved to a separate directory.
Sous-Vide-Zen/backend pull request #94
Opened 2024-06-10 19:23 UTC by menma331

2024-06-13 19:27 UTC, mtedoradze reviewed
Рома, мне кажется, проще сделать в одном файле все фабрики - в файле src/tests/factories/base.py, из остальных файлов с фабриками просто перенеси код в этот, и удали их - мне кажется, нет смысла их плодить. Если хочешь, посоветуйся с Андреем, но я его услышала так, что надо в одном файле все фабрики...
И ты по-моему пропустил еще 2 файла, из которых надо фабрики убрать: test_follow_serializers.py, test_follow_url.py

2024-06-16 15:09 UTC, menma331 commented
> И ты по-моему пропустил еще 2 файла, из которых надо фабрики убрать: test_follow_serializers.py, test_follow_url.py

Убрал.

2024-06-24 19:08 UTC, mtedoradze approved these changes

2024-07-04 11:32 UTC, vBaMnup requested changes
- Не вижу смысла для фабрик делать отдельные файлы, их не так много получается.
- Сейчас дублируются UserFactory и CustomUserFactory

2024-07-04 18:23 UTC, merged